### ISSUE TITLE
Build Project Failed after add dependency

### ISSUE THREAD

**Issue by andrea-liu87** [jordond/compass#36]
After adding these dependency to my project

libs.version.toml :
```
compass = "0.1.8"
compass-geocoder = { module = "dev.jordond.compass:compass-geocoder", version.ref = "compass" }
compass-geocoder-mobile = { module = "dev.jordond.compass:compass-geocoder-mobile", version.ref = "compass" }
compass-geocoder-web-googlemaps = { module = "dev.jordond.compass:compass-geocoder-googlemaps", version.ref = "compass" }
```

build.gradle.kts :
```
val commonMain by getting {
            dependencies {
                api(libs.decompose.router)
                implementation(libs.compass.geocoder)
                implementation(libs.compass.geocoder.web.googlemaps)
..

val mobileMain by creating {
            dependsOn(commonMain)
            androidMain.dependsOn(this)
            iosMain.dependsOn(this)
            dependencies {
                implementation(libs.compass.geocoder.mobile)
            }
        }
```

build project was failed with this log report

> Execution failed for task ':composeApp:transformIosMainCInteropDependenciesMetadataForIde'.
> > Could not resolve all files for configuration ':composeApp:iosMainResolvableDependenciesMetadata'.
>    > Could not find dev.jordond.compass:compass-geocoder-googlemaps:0.1.8.
>      Required by:
>          project :composeApp

perhaps anybody know the cause or fix for this issue

**Comment by andrea-liu87** [comment]
I think it is typo on docs 
compass-geocoder-web-googlemaps = { module = "dev.jordond.compass:compass-geocoder-googlemaps", version.ref = "compass" }

should be
compass-geocoder-web-googlemaps = { module = "dev.jordond.compass:compass-geocoder-web-googlemaps", version.ref = "compass" }

**Comment by jordond** [comment]
You're correct, there was a typo in the docs for the dependency. I've committed the change.

Compass is still under development, so there's gonna be small things like this 😅.
