### ISSUE TITLE
Background Location Tracking

### ISSUE THREAD

**Issue by PicoPocoo** [jordond/compass#90]
Hey there, awesome library!

Do you guys know, how to keep receiving location updates in kmp, while the app is running in the background?
Best regards, and thank you so much for your amazing work!

**Comment by jordond** [comment]
You would have to look on the respective platforms. I imagine for Android you would use [WorkManager](https://developer.android.com/develop/sensors-and-location/location/background) or something similar, no idea about iOS. It's out of the scope of this library.
