### ISSUE TITLE
The badges in the readme don't match the versions you are using

### ISSUE THREAD

**Issue by cristan** [jordond/compass#99]
The most minor issue you'll ever have, but the badges in [your readme](https://github.com/jordond/compass/blob/main/README.MD) don't show the correct version. Kotlin is stating 1.9.23 while you are using 2.0.20. Compose Multiplatform states 1.6.1 while you are using 1.6.11. This makes your project look less well maintained than it actually is.

These versions of dependencies are automatically [updated via a bot](https://github.com/jordond/compass/pull/95), but these bots don't update the readme.

So either change the bots that they update the readme as well, or just don't show version numbers in your badges (so go for https://img.shields.io/badge/kotlin-blue.svg?logo=kotlin and https://img.shields.io/badge/Compose%20Multiplatform-blue ).

**Comment by jordond** [comment]
The README is updated on publish by the [version.sh](https://github.com/jordond/compass/blob/main/.github/version.sh) script. That way the badges match the version used by the latest release.

However the latest release action failed, and never published, so the script didn't run. I'll have to look into why the publish failed

**Comment by jordond** [comment]
Looks like I never actually setup the versioning script in this repo. I'll do that, thanks for pointing it out 👍
